[project]
name = "nba-data-pull"
version = "0.1.0"
description = "Automated data pull for NBA data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nbastatpy>=0.1.8",
    "pandas>=2.2.3",
]
